USE MASTER;
GO
CREATE LOGIN Rafa_2 WITH PASSWORD='1234',
	CHECK_POLICY=OFF;
GO
--
CREATE DATABASE BD_PRUEBA;
GO
USE BD_PRUEBA;
GO

--CREAR UN USUARIO EN LA BD PRUEBA ASOCIADO AL LOGIN
CREATE USER Rafa_2 FOR LOGIN Rafa_2
	WITH DEFAULT_SCHEMA=DBO;
GO
--ASIGNAR UN ROL DE DB AL USUARIO
ALTER ROLE DB_DATAREADER ADD MEMBER Rafa_2
ALTER ROLE DB_datawriter ADD MEMBER Rafa_2

--DAR PERMISO PARA CREAR TABLAS
GRANT CREATE TABLE TO Rafa_2;
revoke CREATE TABLE TO Rafa_2;