# en application.properties
# server.servlet.context-path=/<contexto>
# COPY <war_original>.war /usr/local/tomcat/webapps/<contexto>.war
# Cada cambio que hagas...
# docker build -t <nombre_imagen> .
# docker run --name <nombre_contedor> -d -p 8080:8080 <nombre_imagen>
FROM tomcat:latest

COPY GomezRafaelMiAli.war /usr/local/tomcat/webapps/GomezRafaelMiAli.war